spring:
  redis:
    host: 192.168.157.158
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 100
