server:
  port: 8081

spring:
  application:
    name: flowable
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      url: jdbc:mysql://192.168.157.158:3306/flowable?nullCatalogMeansCurrent=true
      username: root
      password: prc772926
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  async-executor-activate: false
  database-schema-update: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl