server:
  port: 8081

spring:
  datasource:
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      url: jdbc:mysql://192.168.157.158:3306/xuexi
      username: root
      password: prc772926
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #rest≈‰÷√
  #data:
  #  rest:
  #    base-path:
